### ISSUE TITLE
Allow insecure connections to Git repositories

### ISSUE THREAD

**Issue by disi** [stefanprodan/flux-aio#48]
I am trying this in a home lab and the flux container is unable to pull the repository without a valid ssl certificate.

Also I see an issue later adding an own root CA?
Maybe I did not find the documentation to add a configmap with mount of a custom root CA via timoni?

**Comment by stefanprodan** [comment]
@disi please see https://github.com/stefanprodan/flux-aio?tab=readme-ov-file#sync-from-a-self-hosted-git-repository

Let me know if worked for you.

**Comment by disi** [comment]
Hi Stefan, this works perfectly, thank you.

I test in Hyper-V on the laptop, including git and all.
This is super fast using checkpoints, revert, redeploy etc.
