### ISSUE TITLE
Field name typo in serviceaccount.cue

### ISSUE THREAD

**Issue by gordonm** [stefanprodan/flux-aio#68]
Have been enjoying Timoni so far, and was delighted to learn of the Helm interoperability with flux-aio. I was trying to get started on an EKS cluster by following the [Flux installation](https://timoni.sh/flux-aio/#__tabbed_2_2) instructions, but got an `undefined field` error on apply, looks like we need `s/indentity/identity/g` here:

https://github.com/stefanprodan/flux-aio/blob/edd7f4901016a445e12ad15f16d1fe7582d2cf2b/modules/flux-aio/templates/serviceaccount.cue#L13

**Comment by stefanprodan** [comment]
@gordonm thanks for reporting this issue. The fix has been included in https://github.com/stefanprodan/flux-aio/releases/tag/v2.2.2-1
