### ISSUE TITLE
Can flux-aio be used to deploy apps without having git?

### ISSUE THREAD

**Issue by suseendare** [stefanprodan/flux-aio#79]
Context: Our EKS is isolated and cannot connect to git. 
It can connect only to ECR where OCI artifacts are present.
Is it possible to do gitops in this EKS cluster using flux-aio?
Can flux-aio consume OCI artifact as an app manifest?

I see a comment https://github.com/fluxcd/flux2/discussions/4188#discussioncomment-6878553.
However, I am not sure how to proceed here.

Any examples or pointers to documentation, if this is feasible.

**Comment by stefanprodan** [comment]
> Is it possible to do gitops in this EKS cluster using flux-aio?

Yes 💯 

> Can flux-aio consume OCI artifact as an app manifest?

Yes, you would run `flux push artifact` in CI and push the manifests from Git to ECR. Then you would use a Timoni bundle to generate instances of [flux-oci-sync](https://github.com/stefanprodan/flux-aio/tree/main/modules/flux-oci-sync) that configure Flux to fetch and deploy the apps from ECR.

Next week I will add examples for flux-oci-sync to the AIO docs here: https://timoni.sh/flux-aio/
