### ISSUE TITLE
CUE Version breaking build

### ISSUE THREAD

**Issue by suse-coder** [stefanprodan/flux-aio#96]
I am on a talos kubernetes cluster and this worked once but after doing this recent update i get an error:

 timoni bundle apply -f ./charts/cilium/flux-aio-cilium.cue 
6:58PM INF b:flux-aio > applying 2 instance(s)
6:58PM INF b:flux-aio > i:flux > applying module timoni.sh/flux-aio version 2.4.0-0
6:58PM ERR build failed for flux:
timoni.instance.containerEnv.env: Addition of lists is superseded by list.Concat; see https://cuelang.org/e/v0.11-list-arithmetic:
    ./templates/env.cue:47:7

vscode ➜ /workspaces/terraform-talos-openstack_3 (main) $ timoni version
api: timoni.sh/v1alpha1
client: 0.23.0
cue: 0.11.0

![image](https://github.com/user-attachments/assets/4f76a4d2-6a9d-4e99-9a4a-667820e20f29)

**Comment by stefanprodan** [comment]
Fixed in https://github.com/stefanprodan/flux-aio/pull/98

You can use the 2.4.0-1 module to get the fix.
