### ISSUE TITLE
After installing and delete flux-aio, I cant reinstall it in talos with cilium cni

### ISSUE THREAD

**Issue by suse-coder** [stefanprodan/flux-aio#97]
Steps to reproduce:
1. Install on talos kubernetes with flux-aio -> cilium
2. timoni bundle delete -f ./charts/cilium/flux-aio-cilium.cue
3. timoni bundle apply -f ./charts/cilium/flux-aio-cilium.cue does not work. Is stuck. Is not even creating a deploy.
![image](https://github.com/user-attachments/assets/be631788-1824-4804-b2f5-3123c3bad792)

```
// Bundle for using with Talos
bundle: {
	apiVersion: "v1alpha1"
	name:       "flux-aio"
	instances: {
		"flux": {
			module: {
				url:     "oci://ghcr.io/stefanprodan/modules/flux-aio"
				version: "2.4.0-0"
			}
			namespace: "flux-system"
			values: {
                controllers: {
                    helm: enabled:         true
                    kustomize: enabled:    true
                    notification: enabled: true
                }
				hostNetwork:     true
				securityProfile: "privileged"
				env: {
					"KUBERNETES_SERVICE_HOST": "localhost"
					"KUBERNETES_SERVICE_PORT": "7445"
				}
			}
		}
		"cilium-hr": {
			module: {
				url: "oci://ghcr.io/stefanprodan/modules/flux-helm-release"
				version: "2.4.0-0"
			}
			namespace: "flux-system"
			values: {
				repository: url: "https://helm.cilium.io/"
				chart: {
					name:     "cilium"
					version:  "1.16.4"
				}
				helmValues: {
					ipam: mode:               "kubernetes"
					kubeProxyReplacement:     true
					securityContext: capabilities: {
						ciliumAgent: [
							"CHOWN",
							"KILL",
							"NET_ADMIN",
							"NET_RAW",
							"IPC_LOCK",
							"SYS_ADMIN",
							"SYS_RESOURCE",
							"DAC_OVERRIDE",
							"FOWNER",
							"SETGID",
							"SETUID",
						]
						cleanCiliumState: [
							"NET_ADMIN",
							"SYS_ADMIN",
							"SYS_RESOURCE",
						]
						envoy: [
							"NET_ADMIN",
							"NET_BIND_SERVICE",
							"PERFMON",
							"BPF",
						]
					}
					rollOutCiliumPods: true
					operator: rollOutPods: true
					k8sClientRateLimit: {
						qps:   100
						burst: 200
					}
					cgroup: {
						autoMount: enabled: false
						hostRoot:           "/sys/fs/cgroup"
					}
					k8sServiceHost: "localhost"
					k8sServicePort: 7445
                    l2announcements: {
                        enabled: true
                    }
                    envoy: {
                        enabled: true
                        securityContext: capabilities: {
                            keepCapNetBindService: true
                        }
                    }
                    hubble: {
                        relay: {
                            enabled: true
                        }
                        ui: {
                            enabled: true
                        }
                    }
                    gatewayAPI: {
                        enabled: true
                    }
				}
                sync: targetNamespace: "kube-system"
			}
		}
	}
}

```

**Comment by stefanprodan** [comment]
I guess uninstalling cilium has messed up your cluster.

**Comment by stefanprodan** [comment]
The first thing you reported about the concat error, I found the issue and it will be fixed once I merge the PR and do a release. So you can switch back to latest Timoni.

**Comment by stefanprodan** [comment]
Sorry I've closed the wrong issue.

**Comment by stefanprodan** [comment]
So the safest way to remove Flux without uninstalling any managed resources such as Cilium, you can run `flux uninstall`, documented in the readme here: https://github.com/stefanprodan/flux-aio?tab=readme-ov-file#uninstall-flux

The timoni command will uninstall Cilium which I suspect it has broken you cluster.

**Comment by suse-coder** [comment]
I needed to unistall:
kubectl delete crd alerts.notification.toolkit.fluxcd.io --force --grace-period=0
kubectl delete crd buckets.source.toolkit.fluxcd.io --force --grace-period=0
kubectl delete crd gitrepositories.source.toolkit.fluxcd.io --force --grace-period=0
kubectl delete crd imagepolicies.image.toolkit.fluxcd.io --force --grace-period=0
kubectl delete crd imagerepositories.image.toolkit.fluxcd.io --force --grace-period=0
kubectl delete crd imageupdateautomations.image.toolkit.fluxcd.io --force --grace-period=0
kubectl delete crd kustomizations.kustomize.toolkit.fluxcd.io --force --grace-period=0
kubectl delete crd ocirepositories.source.toolkit.fluxcd.io --force --grace-period=0
kubectl delete crd providers.notification.toolkit.fluxcd.io --force --grace-period=0
kubectl delete crd receivers.notification.toolkit.fluxcd.io --force --grace-period=0

**Comment by suse-coder** [comment]
Is it possible to add a section for talos kubernetes that people know that one needs to first do a:
 kubectl create namespace flux-system
 kubectl label namespace flux-system pod-security.kubernetes.io/enforce=privileged pod-security.kubernetes.io/audit=privileged pod-security.kubernetes.io/warn=privileged --overwrite

**Comment by suse-coder** [comment]
Btw. Flux-AIO + Talos is awesome. Just need a better app store like helm has and on bundle apply saying for what resources it waits on.

**Comment by stefanprodan** [comment]
flux-aio `v2.4.0-2` should work without any kubectl commands on Talos, readme updated.
